# Render Blueprint Specification
# https://render.com/docs/blueprint-spec

services:
  # --- Kafka Stack ---
  - name: zookeeper
    type: pserv # Private Service
    image:
      url: confluentinc/cp-zookeeper:7.5.0
    envVars:
      - key: ZOOKEEPER_CLIENT_PORT
        value: 2181
      - key: ZOOKEEPER_TICK_TIME
        value: 2000

  - name: kafka
    type: pserv
    image:
      url: confluentinc/cp-kafka:7.5.0
    envVars:
      - key: KAFKA_BROKER_ID
        value: 1
      - key: KAFKA_ZOOKEEPER_CONNECT
        value: zookeeper:2181
      - key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: PLAINTEXT:PLAINTEXT
      - key: KAFKA_ADVERTISED_LISTENERS
        value: PLAINTEXT://kafka:9092
      - key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: 1
      - key: KAFKA_AUTO_CREATE_TOPICS_ENABLE
        value: "true"

  # --- Our Python Application ---
  - name: data-processor
    type: pserv
    dockerfilePath: ./Dockerfile
    startCommand: "python3 -m pipeline.kafka_consumer"
    envVars:
      - fromGroup: project-secrets # Pulls secrets from the group
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: kafka:9092
      - key: DATABASE_URL # Gets the internal connection string
        fromService:
          type: postgres
          name: project-db
          property: connectionString

  # --- Monitoring Stack ---
  - name: prometheus
    type: pserv
    image:
      url: prom/prometheus:latest
    startCommand: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    disk:
      name: prometheus-data
      mountPath: /prometheus
      sizeGB: 1

  - name: grafana
    type: web # Publicly accessible Web Service
    image:
      url: grafana/grafana:latest

databases:
  - name: project-db
    plan: free