global:
  scrape_interval: 15s # Scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'data-processor-app'
    # This is the target. 'data-processor' is our Python app's service name
    # in Docker Compose, and 8000 is the port we exposed in the code.
    static_configs:
      - targets: ['data-processor:8000']